import { Font, StyleSheet } from "@react-pdf/renderer";

export const CORES = {
  azulPrimario: "#0071E3",
  azulAcao: "#006AE0",
  azulEscuro: "#005CB3",
  azulClaro: "#E7F1FC",
  verdeSucesso: "#3AB97A",
  verdeFundo: "#E4F5EB",
  verdeEscuro: "#1A6E3C",
  amareloAtencao: "#A86A00",
  amareloFundo: "#FFF6E2",
  amareloBorda: "#E2C580",
  texto: "#1E1E1E",
  cinzaSuave: "#5F6875",
  cinzaLinha: "#D9DDE3",
  fundo: "#F8F9FB",
} as const;

const INTER_SOURCE =
  "https://raw.githubusercontent.com/google/fonts/main/ofl/inter/Inter%5Bopsz%2Cwght%5D.ttf";
Font.register({ family: "Inter", src: INTER_SOURCE, fontWeight: 400 });
Font.register({ family: "Inter Bold", src: INTER_SOURCE, fontWeight: 700 });
export const FONTES = {
  display: "Inter",
  body: "Inter",
  bold: "Inter Bold",
} as const;

// Valores em pontos equivalentes aos pixels do mockup (72/96), preservando sua escala em A4.
export const styles = StyleSheet.create({
  page: {
    paddingTop: 30,
    paddingRight: 36,
    paddingBottom: 24,
    paddingLeft: 36,
    fontFamily: FONTES.body,
    fontSize: 10.5,
    lineHeight: 1.45,
    color: CORES.texto,
    backgroundColor: "#FFFFFF",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: 10.5,
    marginBottom: 16.5,
    borderBottomWidth: 2,
    borderBottomColor: CORES.azulPrimario,
  },
  brand: { fontFamily: FONTES.bold, fontSize: 16.5, color: CORES.azulPrimario },
  brandSub: {
    marginTop: 3,
    fontSize: 7.9,
    letterSpacing: 0.9,
    color: CORES.cinzaSuave,
    textTransform: "uppercase",
  },
  meta: { textAlign: "right", color: CORES.cinzaSuave, fontSize: 9 },
  metaNumber: { fontFamily: FONTES.bold, color: CORES.texto, marginBottom: 2 },
  title: {
    fontFamily: FONTES.bold,
    color: CORES.azulPrimario,
    fontSize: 18,
    marginTop: 2,
  },
  reference: {
    color: CORES.cinzaSuave,
    fontSize: 10.1,
    marginTop: 4.5,
    marginBottom: 9,
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5.25,
    borderBottomWidth: 0.5,
    borderBottomColor: CORES.cinzaLinha,
    paddingBottom: 2,
    marginTop: 6,
    marginBottom: 4,
  },
  sectionMark: {
    width: 3,
    height: 10.5,
    backgroundColor: CORES.azulPrimario,
    borderRadius: 1.5,
  },
  sectionTitle: {
    fontFamily: FONTES.bold,
    color: CORES.azulPrimario,
    fontSize: 9.75,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  hero: {
    flexDirection: "row",
    alignItems: "center",
    borderLeftWidth: 4,
    borderRadius: 7.5,
    padding: 13,
    marginBottom: 7,
  },
  heroIcon: {
    width: 39,
    height: 39,
    borderRadius: 19.5,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 15,
    fontFamily: FONTES.bold,
    fontSize: 19.5,
  },
  heroContent: { flexGrow: 1, flexBasis: 0 },
  heroLabel: {
    fontFamily: FONTES.bold,
    fontSize: 8.25,
    letterSpacing: 0.95,
    textTransform: "uppercase",
  },
  heroValue: {
    fontFamily: FONTES.bold,
    fontSize: 27,
    lineHeight: 1.05,
    marginTop: 3,
  },
  heroSub: { color: CORES.cinzaSuave, marginTop: 3.75, fontSize: 10.1 },
  progressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    color: CORES.cinzaSuave,
    fontSize: 8.6,
    marginBottom: 3.75,
  },
  progressTrack: {
    height: 7.5,
    backgroundColor: CORES.cinzaLinha,
    borderRadius: 3.75,
  },
  progressFill: {
    height: 7.5,
    backgroundColor: CORES.verdeSucesso,
    borderRadius: 3.75,
  },
  progressLegend: {
    flexDirection: "row",
    justifyContent: "space-between",
    color: CORES.cinzaSuave,
    fontSize: 8.25,
    marginTop: 3,
  },
  alert: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#FFE9C4",
    borderWidth: 0.7,
    borderColor: CORES.amareloBorda,
    borderRadius: 6,
    padding: 8,
    marginBottom: 7,
  },
  alertIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    color: CORES.amareloAtencao,
    fontFamily: FONTES.bold,
    fontSize: 18,
    marginRight: 10.5,
  },
  alertContent: { flexGrow: 1, flexBasis: 0 },
  alertTitle: {
    color: CORES.amareloAtencao,
    fontFamily: FONTES.bold,
    fontSize: 10.1,
    marginBottom: 3,
  },
  alertText: { fontSize: 9.4 },
  dataGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    backgroundColor: CORES.fundo,
    borderRadius: 4.5,
    padding: 7,
  },
  dataItem: {
    width: "33.333%",
    paddingRight: 12,
    marginBottom: 4,
    fontSize: 10.1,
  },
  dataLabel: {
    fontFamily: FONTES.bold,
    fontSize: 7.9,
    color: CORES.cinzaSuave,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  paragraph: {
    marginBottom: 4,
    textAlign: "justify",
    fontSize: 10.1,
    lineHeight: 1.5,
  },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  chip: {
    width: "18.9%",
    backgroundColor: CORES.azulClaro,
    borderLeftWidth: 2.5,
    borderLeftColor: CORES.azulPrimario,
    borderRadius: 3,
    padding: 5,
  },
  chipLabel: {
    fontFamily: FONTES.bold,
    fontSize: 8.25,
    color: CORES.cinzaSuave,
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  chipValue: {
    marginTop: 2.25,
    color: CORES.azulEscuro,
    fontFamily: FONTES.bold,
    fontSize: 9.75,
  },
  bullet: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 2.5,
  },
  bulletMark: {
    width: 4.5,
    height: 4.5,
    borderRadius: 2.25,
    backgroundColor: CORES.azulPrimario,
    marginTop: 5.2,
    marginRight: 8,
  },
  bulletText: { flexGrow: 1, flexBasis: 0, fontSize: 9.75 },
  checklist: { flexDirection: "row", gap: 16.5 },
  checklistColumn: { flexGrow: 1, flexBasis: 0 },
  reasonRow: { flexDirection: "row", gap: 7.5 },
  reasonCard: {
    flexGrow: 1,
    flexBasis: 0,
    backgroundColor: CORES.fundo,
    borderLeftWidth: 2.5,
    borderLeftColor: CORES.amareloAtencao,
    borderRadius: 3,
    padding: 9,
  },
  reasonTitle: {
    fontFamily: FONTES.bold,
    color: CORES.amareloAtencao,
    fontSize: 9.4,
    fontWeight: 700,
  },
  reasonText: {
    color: CORES.cinzaSuave,
    fontSize: 9.4,
    marginTop: 3,
    lineHeight: 1.4,
  },
  contact: {
    marginTop: 7,
    padding: 8,
    backgroundColor: CORES.azulPrimario,
    borderRadius: 6,
    color: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  contactMessage: {
    flexGrow: 1,
    flexBasis: 0,
    paddingRight: 10,
    fontSize: 10.1,
  },
  contactValue: {
    fontFamily: FONTES.bold,
    color: "#FFFFFF",
    marginLeft: 9,
    fontSize: 10.1,
  },
  footer: {
    marginTop: 6,
    paddingTop: 5,
    borderTopWidth: 0.7,
    borderTopColor: CORES.cinzaLinha,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  footerBrand: { fontFamily: FONTES.bold, color: CORES.texto, fontSize: 9.4 },
  footerRight: { textAlign: "right", color: CORES.cinzaSuave, fontSize: 8.25 },
  disclaimer: {
    marginTop: 3,
    color: CORES.cinzaSuave,
    fontSize: 7.9,
    textAlign: "center",
    lineHeight: 1.5,
  },
});
